
project_id = "mrleaafljzzyorivozpm"

[functions.generate_requirements]
verify_jwt = false

[functions.generate-app-flow]
verify_jwt = false

[functions.generate-tech-stack]
verify_jwt = false

[functions.generate-frontend-guidelines]
verify_jwt = false

[functions.generate-backend-structure]
verify_jwt = false

[functions.generate-file-structure]
verify_jwt = false

[functions.generate-implementation-plan]
verify_jwt = false

[functions.generate-app-outline]
verify_jwt = false

[functions.generate-app-ideas]
verify_jwt = false

[functions.generate-title]
verify_jwt = false


[functions.stripe-checkout-session]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-checkout-session/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-checkout-session/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-checkout-session/*.html" ]

[functions.stripe-billing-portal]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-billing-portal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-billing-portal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-billing-portal/*.html" ]

[functions.stripe-subscriptions]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-subscriptions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-subscriptions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-subscriptions/*.html" ]

[functions.edna-sso]
enabled = true
verify_jwt = true
import_map = "./functions/edna-sso/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/edna-sso/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/edna-sso/*.html" ]

[functions.sso-login]
enabled = true
verify_jwt = true
import_map = "./functions/sso-login/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sso-login/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sso-login/*.html" ]
