
project_id = "mrleaafljzzyorivozpm"

[functions.generate_requirements]
verify_jwt = false

[functions.generate-app-flow]
verify_jwt = false

[functions.generate-tech-stack]
verify_jwt = false

[functions.generate-frontend-guidelines]
verify_jwt = false
