// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrleaafljzzyorivozpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybGVhYWZsanp6eW9yaXZvenBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MzU5MDQsImV4cCI6MjA1NDMxMTkwNH0.qaC2Co5xIonoLzEkzJ3SUn8e14o89z_dsYzsoSZX63g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);